### PR TITLE
Limit State to ExtractorEngine

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by marcovzla** [comment]
@kwalcock does this PR replace #95 ?

**Comment by kwalcock** [comment]
This #112 incorporates #95 and #108.  It's a straight line if you want them all, you can skip to the end.

**Comment by marcovzla** [comment]
:shipit:

**Comment by kwalcock** [comment]
@marcovzla, when it says "marcovzla merged commit cb873fc into master 42 minutes ago" and commit cb873fc is not one in the list, what has happened?  It seems like some information is being lost.

**Pull request merged**
