### PR TITLE
feature/config.apply-for-less-red-squiggles

### PR DESCRIPTION
**Pull request by nezda**
Explicitly say `Config.apply[MyType]` (rather than just `Config[MyType]`) so IntelliJ won't falsely flag errors ("red squiggles") because its type inference is currently inferior to `scalac`.

- errors flagged were:  "No implicits found for parameter evidence$1: ConfigFieldReader[A_]" / "Ambiguous implicits for parameter evidence$1: ConfigFieldReader[A_]"
- likely IntelliJ bug https://youtrack.jetbrains.com/issue/SCL-17529 (vote for it!)

Discussion https://github.com/lum-ai/odinson/discussions/289#discussioncomment-766181

regex find and replace (poor man's [structural search and replace](https://www.jetbrains.com/help/idea/structural-search-and-replace.html)):
* find: `([a-zA-Z]*[cC]onfig)(\[[A-Za-z\[\]]+\] *\()`
* replace: `$1.apply$2`

### CODE REVIEW

**Comment by BeckySharp** [comment]
hey, @nezda once I clicked the button to run the CI checks (I had to since it was your first time contributing), it complained about the linting (something we recently added).
Would you please run this on your branch and re-push?
```sbt scalafmtAll && sbt scalafmtCheckAll```

**Comment by nezda** [comment]
I’ll fix that PR tomorrow

**Comment by nezda** [comment]
> sbt scalafmtAll && sbt scalafmtCheckAll

fwiw I noticed `time (sbt scalafmtAll scalafmtCheckAll)` is much faster than `time (sbt scalafmtAll && sbt scalafmtCheckAll)` - clearly some redundant loading in the first one

**Comment by myedibleenso** [comment]
@nezda , thanks for this!  While our docker images use Java 11, our CI tests [still use Java 8](https://github.com/lum-ai/odinson/blob/f32c25fd1dd6b9e7c1b813bcc455b2ef620add26/.github/workflows/ci.yml#L18).  I believe `Path.of` was introduced in Java 11:

- https://github.com/nezda/odinson/blob/05e5b32211e7b6bfff20120869b9898c91951813/core/src/main/scala/ai/lum/odinson/OdinsonIndexWriter.scala#L275

Would you please revert this change to use `File` for the time being?  The team has discussed finally moving to Java 11, but I think we should hold off and make that change in a separate PR.

Also, based on your benchmark, please feel free to update the docs page regarding `sbt scalafmtAll && sbt scalafmtCheckAll` -> `sbt scalafmtAll scalafmtCheckAll`:

- https://github.com/lum-ai/odinson/blob/b2177202d80a6060a709ab4aa31f3f5623706470/docs/contributing.md

**Comment by nezda** [comment]
Oops, confirmed locally with `sdk use java 8.0.242.hs-adpt` and `sbt clean test`:

```
[error] /Users/nezda/code/odinson.git/core/src/main/scala/ai/lum/odinson/OdinsonIndexWriter.scala:275:41: value of is not a member of object java.nio.file.Path
[error]         val dir = FSDirectory.open(Path.of(path))
[error]                                         ^
[error] one error found
[error] (core / Compile / compileIncremental) Compilation failed
```

I presume this got caught by CI tests?

In any case, I switched it to `Paths.get()` and seems to build fine - all good?

`sbt scalafmtAll && sbt scalafmtCheckAll`  -> `sbt scalafmtAll scalafmtCheckAll` for speed 🐎  done too

There were squiggles in there i squashed too:

image

I'm happy to change

**Review by BeckySharp — APPROVED** [review]
LGTM, thanks!

**Comment by BeckySharp** [comment]
@myedibleenso shall I push the button or did you want to check it over once more?

**Comment by myedibleenso** [comment]
Perfect.  Thanks, @nezda !

**Pull request merged**
