### PR TITLE
**testing codcov**

### PR DESCRIPTION
**Pull request by gcgbarbosa**
this is just a test.

### CODE REVIEW

**Comment by gcgbarbosa** [comment]
:(

**Comment by gcgbarbosa** [comment]
@marco and @BeckySharp this looks cool.

**Comment by gcgbarbosa** [comment]
@BeckySharp check commit 961cc0a. It has a ‘v’ mark informing that the tests have passed.

**Comment by BeckySharp** [comment]
Cool!  hey -- when I looked at the report, I was able to see how many lines were "hit" and not, but not which lines were hit, is there a way to do that, maybe even with a diff view?

**Comment by gcgbarbosa** [comment]
I don’t know if I understood, but the image I sent over slack has this view of which lines were hit and which were not.

**Comment by marcovzla** [comment]
@gcgbarbosa Can you please add a line to the CHANGES.md file that states what was added with this PR?
Also, is it necessary to change sbt's version?

**Comment by gcgbarbosa** [comment]
> @gcgbarbosa Can you please add a line to the CHANGES.md file that states what was added with this PR?
> Also, is it necessary to change sbt's version?

I am following what they recommend. I don't know if it works with another version.
Should I try keeping the version we were using before?
https://github.com/scoverage/sbt-scoverage

**Comment by myedibleenso** [comment]
@gcgbarbosa, we want to avoid downgrading sbt (that sort of change is in the wrong direction).  Please try testing things with the prior version.

**Comment by gcgbarbosa** [comment]
@myedibleenso, changed it back to 1.2.6. Tests work on my machine. Let's see if it will work with git actions too.

**Comment by gcgbarbosa** [comment]
it worked! @myedibleenso

**Pull request merged**
