### PR TITLE
replaced sys.error and silenced warning

### PR DESCRIPTION
**Pull request by BeckySharp**
FYI @kwalcock , I couldn't find the Exceptions you mentioned in #197

### CODE REVIEW

**Comment by kwalcock** [comment]
They are still in a branch, but they will need the cause argument in order to inherit from OdinsonException.

**Comment by BeckySharp** [comment]
@kwalcock -- does this work for your needs in #197 ?
SO was my bff here, feel free to edit!

**Comment by kwalcock** [comment]
Thank you!  It has been so long since I've seen a null.  It seems like a relic from the past.

**Review by kwalcock — APPROVED** [review]

**Review by marcovzla — APPROVED** [review]
Thanks!

**Pull request merged**
