### PR TITLE
Documentation about StringField unsupported for metadata

### PR DESCRIPTION
**Pull request by BeckySharp**
Addresses #328 

Documentation failed to explain that StringFields are not supported in the Odinson Document metadata.  @marcovzla  can correct me if I'm wrong, but I think it has to do with how we build Lucene queries against text (i.e., to support the contains queries etc.)
If there is substantial need for supporting this, we can reconsider.
In the meantime, users should consider reframing their metadata as another field type (e.g., TokensField).
Note that this implies that users will tokenize their text. That is, "Biology Magazine" should not be represented as a list of one token that is `"Biology Magazine"`, but rather as `["Biology", "Magazine"]` (or another tokenization).

Added:
- info to the Docs pages
- a logger info statement that is logged if you (a) try to index a Document with user-defined StringField in the metadata or (b) try to use the `addMetadata()` method in `Document` class with a StringField.
- tests demonstrating the right and wrong behavior

### CODE REVIEW

**Comment by BeckySharp** [comment]
also edited one of the example doc jsons (bad-character) to use TokensFields instead of StringFields

**Comment by BeckySharp** [comment]
Also, please note comment here:
https://github.com/lum-ai/odinson/issues/328#issuecomment-901600227

do we need to update something(s) in the backend?

**Comment by myedibleenso** [comment]
@BeckySharp , you asked about the REST API.  I think that minimally the following changes should be made:

Remove this line:
https://github.com/lum-ai/odinson/blob/3c5326be908e0648120f329e287c8667af0df4ce/backend/app/controllers/OdinsonController.scala#L857

Refactor this code to not use a parent query and possibly parse/compile the rule file in a way that is compatible with your changes to parent/metadata queries:
https://github.com/lum-ai/odinson/blob/3c5326be908e0648120f329e287c8667af0df4ce/backend/app/controllers/OdinsonController.scala#L881-L894

For consistency, @danebell, [`parentQuery` in the OpenAPI spec should be replaced with `metadataQuery`.  There's also a section describing `parentQuery` as a Lucene query.  This is no longer true.  Really we should **include a link to documentation describing how metadata queries work (what is supported, etc.)**. ](https://github.com/lum-ai/odinson/blob/master/backend/public/schema/odinson.yaml)

**Comment by myedibleenso** [comment]
@BeckySharp @danebell , you can disregard my last message. I've taken care of those changes.

**Review by myedibleenso — APPROVED** [review]

**Pull request merged**
