### PR TITLE
Address contributions in the README.md file

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
This should wait until the CLA has been deployed.  There is a link in it that won't work until that has been done.

**Comment by BeckySharp** [comment]
@kwalcock (a) did you see my other PR? and (b) man, look at the drop in test coverage!  You should have written a test for the readme! :D

**Comment by kwalcock** [comment]
From now on for every n lines of code you add, you have to remove n + 1.

**Comment by kwalcock** [comment]
Now Becky has to sign because she has a commit.  Ha ha.  You're it!

**Comment by BeckySharp** [comment]
> Now Becky has to sign because she has a commit. Ha ha. You're it!

hahaha that's hilarious, yet potentially problematic, right?  should I have the ability to invalidate your work simply bc i commented on your message?

**Comment by kwalcock** [comment]
You have a commit in there as well as a comment.  That's what you get for adding that comma to my beautiful text.

**Comment by BeckySharp** [comment]
> You have a commit in there as well as a comment. That's what you get for adding that comma to my beautiful text.

ah, i forgot about that!!

**Pull request merged**
