### PR TITLE
Integrate state

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
Only the bottom three commits are pertinent.  The others are/were part of #82.  They may be repeated here because of the unusual merge back then.

I notice that IntelliJ is reformatting the import statements when it adds a new one so that some spaces around { } are lost.  I'll let that be.

The labels are somewhat unclear.  The rules have them, the extractor has them, and the state has them.  Some of them are the same.  See TestEvent for an example when one was set manually.

**Comment by marcovzla** [comment]
@kwalcock after I merged #94 there is a conflict in this PR.
Can you look at it please?
Thanks!

**Comment by kwalcock** [comment]
Too many cooks in the kitchen or I'm stepping on my own toes, whichever.  Thanks, Marco.

**Comment by kwalcock** [comment]
@marcovzla, aren't the Mentions that are being returned from extractMentions the very things that might be in overabundance and part of the reason that the state is a database rather than a collection of Mentions?  Or is the overabundance at some lower level than that?

**Comment by kwalcock** [comment]
These changes are just baby steps so that @marcovzla can stop me from going too far in the wrong direction.  There are more PRs waiting already.  Don't let the incompleteness prevent a merge.

**Comment by marcovzla** [comment]
> @marcovzla, aren't the Mentions that are being returned from extractMentions the very things that might be in overabundance and part of the reason that the state is a database rather than a collection of Mentions? Or is the overabundance at some lower level than that?

I am not sure I understand the question. Can you give me some context? or we can do it on a call.

**Comment by kwalcock** [comment]
I will delete this PR shortly as being superfluous.

**Pull request closed without merging**
