### PR TITLE
adding/modifying tests

### PR DESCRIPTION
**Pull request by maxaalexeeva**
- added tests for OdinsonController methods and endpoints 
- added tests to check if IndexDocuments write the correct meta files (dependencies.txt and buildinfo.json, which includes the "version" field)
- adjusted TestIndexWriter to avoid overwriting the main index / the test is done with a temp directory
- corrected an error from the previous pr (reading the arg in IndexDocuments **after** confirming that the argument was passed)
- deleted unused imports 
- added a test sentence to the backend test document to match the test grammar

### CODE REVIEW

**Comment by maxaalexeeva** [comment]
@myedibleenso, I think now the endpoint tests work the way you wanted them.

**Review by myedibleenso — CHANGES_REQUESTED** [review]
@maxaalexeeva , this looks great!  Can you please update the changes log?

**Comment by maxaalexeeva** [comment]
Yes! I'm hoping to get around to it later today.

**Comment by maxaalexeeva** [comment]
@myedibleenso, I am not sure about the level of granularity of changes to document. I added a couple of major-ish ones, but would I add the disabling of OdinsonProviderModule? What about getting rid of odinson contexts? Or details on new tests? (e.g., the test for the buildinfo.json having the "version" field?

**Review by myedibleenso — APPROVED** [review]
Thanks!

**Pull request merged**
