### PR TITLE
Removed Travis config in favor of GitHub Actions

### PR DESCRIPTION
**Pull request by myedibleenso**
# Summary of changes

- removed .travis.yml
- updated badge for test and CI checks run via GitHub Actions

### CODE REVIEW

**Comment by kwalcock** [comment]
I usually think that Marco is the one who needs to be happy about Odinson PRs, but if he isn't offended, I can look at the small ones.  The punctuation of the changed line seems to have changed and if I click on the icon, it just shows the image in a window rather than anything useful, unlike the other icon.  Something might be off, possibly me.

**Comment by myedibleenso** [comment]
>I usually think that Marco is the one who needs to be happy about Odinson PRs, but if he isn't offended, I can look at the small ones.

I think this sort of thing can get shuffled through without the Supreme Leader personally signing off, though substantive changes to Odinson (ex. new features/behavior) warrant more eyes/deeper review.

>The punctuation of the changed line seems to have changed and if I click on the icon, it just shows the image in a window rather than anything useful, unlike the other icon. Something might be off, possibly me.

Ack! That certainly wasn't intended.  I copied that line from the GitHub Actions badge generator (with a slight modification to the display text).  This might require some digging to produce a magic link to log of the most recent CI run...

**Comment by myedibleenso** [comment]
I think it's fixed now.

**Comment by myedibleenso** [comment]
@kwalcock

**Review by kwalcock — APPROVED** [review]

**Pull request merged**
