### PR TITLE
Organizing core tests

### PR DESCRIPTION
**Pull request by gcgbarbosa**
#79 

Tests were split into 6 groups:

1. events
2. foundations (basic tests)
3. patterns (this may change in the future)
4. serialization
5. traversals
6. util

Now all tests extend BaseSpec
Recommended [here](https://www.scalatest.org/user_guide/defining_base_classes).

The current TestHelper became an object inside a trait that returns the shared mixtures for all tests.

Subsequent fixtures are going to be implemented as functions.
Recommended [here](https://blog.softwaremill.com/fixtures-in-scala-three-simple-ways-to-reduce-your-test-boilerplate-5eb60ffe883).

### CODE REVIEW

**Comment by marcovzla** [comment]
@gcgbarbosa can you please merge master into this branch?

**Comment by gcgbarbosa** [comment]
@marcovzla done.

**Comment by marcovzla** [comment]
Can you change the note in `CHANGES.md` from `Added` to `Changed` please?

**Comment by marcovzla** [comment]
Thanks!

**Pull request merged**
